---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
#
-

  # Hosts: where our play will run and options it will run with
  hosts: linux
  
  # Roles: list of roles to be imported into the play 
  roles:
    - { role: webapp, target_dir: "{%- if ansible_distribution == 'CentOS' -%}/usr/share/nginx/html{%- elif ansible_distribution == 'Ubuntu' -%}/var/www/html{%- endif %}" }

# Three dots indicate the end of a YAML document
...
