---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: ubuntu-c
  
  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Pull images
      docker_image:
        docker_host: tcp://docker:2375
        name: "{{ item }}"
        source: pull
      with_items:
        - centos
        - ubuntu
        - redis
        - nginx
        # n.b. large image, >1GB
        - wernight/funbox

    - name: Create a customised index.html
      copy:
        dest: /shared/index.html
        mode: 0644
        content: |
          Customised page for nginxcustomised

    - name: Create a customised Dockerfile
      copy:
        dest: /shared/Dockerfile
        mode: 0644
        content: |
          FROM nginx
          COPY index.html /usr/share/nginx/html/index.html

    - name: Build a customised image
      docker_image:
        docker_host: tcp://docker:2375
        name: nginxcustomised:latest
        source: build
        build:
          path: /shared
          pull: yes
        state: present
        force_source: yes

    - name: Create an nginxcustomised container
      docker_container:
        docker_host: tcp://docker:2375
        name: containerwebserver
        image: nginxcustomised:latest
        ports:
          - 80:80
        container_default_behavior: no_defaults
        recreate: yes

# Three dots indicate the end of a YAML document
...
